server:
  port: 8080
spring:
  flyway:
    enabled: false
#    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/teamup
    username: teamUp
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

